## Import

In [1]:
import random
import pandas as pd
import numpy as np
import os
import cv2

from sklearn import preprocessing
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm.auto import tqdm

import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2
import torchvision.models as models

from sklearn.metrics import f1_score, accuracy_score
from sklearn.metrics import classification_report

import warnings
warnings.filterwarnings(action='ignore')
os.chdir('../')

In [2]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

## Hyperparameter Setting

In [3]:
CFG = {
    'IMG_SIZE':128,
    'EPOCHS':5,
    'LEARNING_RATE':3e-4,
    'BATCH_SIZE':64,
    'SEED':41
}

## Fixed RandomSeed

In [4]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True

seed_everything(CFG['SEED']) # Seed 고정

## Data Load & Train/Validation Split

In [5]:
all_df = pd.read_csv('./train.csv')

In [6]:
train_df, val_df, _, _ = train_test_split(all_df, all_df['cat3'], test_size=0.2, random_state=CFG['SEED'])

## Label-Encoding

In [7]:
le = preprocessing.LabelEncoder()
le.fit(train_df['cat3'].values)

LabelEncoder()

In [8]:
train_df['cat3'] = le.transform(train_df['cat3'].values)
val_df['cat3'] = le.transform(val_df['cat3'].values)

## Vectorizer

In [9]:
vectorizer = CountVectorizer(max_features=4096)

In [10]:
train_vectors = vectorizer.fit_transform(train_df['overview'])
train_vectors = train_vectors.todense()

val_vectors = vectorizer.transform(val_df['overview'])
val_vectors = val_vectors.todense()

In [11]:
train_vectors.shape

(13588, 4096)

In [12]:
val_vectors.shape

(3398, 4096)

## CustomDataset

In [13]:
class CustomDataset(Dataset):
    def __init__(self, img_path_list, text_vectors, label_list, transforms, infer=False):
        self.img_path_list = img_path_list
        self.text_vectors = text_vectors
        self.label_list = label_list
        self.transforms = transforms
        self.infer = infer
        
    def __getitem__(self, index):
        # NLP
        text_vector = self.text_vectors[index]
        
        # Image
        img_path = self.img_path_list[index]
        image = cv2.imread(img_path)
        
        if self.transforms is not None:
            image = self.transforms(image=image)['image']
        
        # Label
        if self.infer:
            return image, torch.Tensor(text_vector).view(-1)
        else:
            label = self.label_list[index]
            return image, torch.Tensor(text_vector).view(-1), label
        
    def __len__(self):
        return len(self.img_path_list)

In [14]:
train_transform = A.Compose([
                            A.Resize(CFG['IMG_SIZE'],CFG['IMG_SIZE']),
                            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
                            ToTensorV2()
                            ])

test_transform = A.Compose([
                            A.Resize(CFG['IMG_SIZE'],CFG['IMG_SIZE']),
                            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
                            ToTensorV2()
                            ])

In [15]:
train_dataset = CustomDataset(train_df['img_path'].values, train_vectors, train_df['cat3'].values, train_transform)
train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True, num_workers=6)

val_dataset = CustomDataset(val_df['img_path'].values, val_vectors, val_df['cat3'].values, test_transform)
val_loader = DataLoader(val_dataset, batch_size=CFG['BATCH_SIZE'], shuffle=False, num_workers=6)

## Model Define

In [16]:
class CustomModel(nn.Module):
    def __init__(self, num_classes=len(le.classes_)):
        super(CustomModel, self).__init__()
        # Image
        self.cnn_extract = nn.Sequential(
            nn.Conv2d(3, 8, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(8, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(32, 64, kernel_size=4, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        # Text
        self.nlp_extract = nn.Sequential(
            nn.Linear(4096, 2048),
            nn.ReLU(),
            nn.Linear(2048, 1024),
        )
        # Classifier
        self.classifier = nn.Sequential(
            nn.Linear(4160, num_classes)
        )
            

    def forward(self, img, text):
        img_feature = self.cnn_extract(img)
        img_feature = torch.flatten(img_feature, start_dim=1)
        text_feature = self.nlp_extract(text)
        feature = torch.cat([img_feature, text_feature], axis=1)
        output = self.classifier(feature)
        return output

## Train

In [17]:
def train(model, optimizer, train_loader, val_loader, scheduler, device):
    model.to(device)

    criterion = nn.CrossEntropyLoss().to(device)
    best_score = 0
    best_model = None
    
    for epoch in range(1,CFG["EPOCHS"]+1):
        model.train()
        train_loss = []
        for img, text, label in tqdm(iter(train_loader)):
            print(label)
            img = img.float().to(device)
            text = text.to(device)
            label = label.to(device)
            
            optimizer.zero_grad()

            model_pred = model(img, text)
            
            loss = criterion(model_pred, label)

            loss.backward()
            optimizer.step()

            train_loss.append(loss.item())

        tr_loss = np.mean(train_loss)
            
        val_loss, val_score = validation(model, criterion, val_loader, device)
            
        print(f'Epoch [{epoch}], Train Loss : [{tr_loss:.5f}] Val Loss : [{val_loss:.5f}] Val Score : [{val_score:.5f}]')
        
        if scheduler is not None:
            scheduler.step()
            
        if best_score < val_score:
            best_score = val_score
            best_model = model
    
    return best_model

In [18]:
def score_function(real, pred):
    return f1_score(real, pred, average="weighted")

def validation(model, criterion, val_loader, device):
    model.eval()
    
    model_preds = []
    true_labels = []
    
    val_loss = []
    
    with torch.no_grad():
        for img, text, label in tqdm(iter(val_loader)):
            img = img.float().to(device)
            text = text.to(device)
            label = label.to(device)
            
            model_pred = model(img, text)
            
            loss = criterion(model_pred, label)
            
            val_loss.append(loss.item())
            
            model_preds += model_pred.argmax(1).detach().cpu().numpy().tolist()
            true_labels += label.detach().cpu().numpy().tolist()
        
    test_weighted_f1 = score_function(true_labels, model_preds)
    return np.mean(val_loss), test_weighted_f1

## Run!!

In [19]:
model = CustomModel()
model.eval()
optimizer = torch.optim.Adam(params = model.parameters(), lr = CFG["LEARNING_RATE"])
scheduler = None

infer_model = train(model, optimizer, train_loader, val_loader, scheduler, device)

  0%|          | 0/213 [00:00<?, ?it/s]

tensor([ 44,  90, 118,  86, 118,  85, 121, 110,  31,  31, 105,  69,  73,  94,
        119, 119,  90,  71,  73,  41,  85,  73,  85,  40, 118, 118,  53,  90,
         73,  15, 100, 118,  41,   8,  52,   0, 116, 118, 118,  73, 118, 113,
        118,  86,  20,  40, 118, 118,  85,  52,   4,  73, 118,  37,  84, 118,
         90,  73,  33,  53,  54,  90,  73,  54])
tensor([ 58,  11,   3,  73, 118, 118,  73, 118,  86, 118, 118, 118,  29,  93,
         41,  73, 119, 118,  84,  44,  73, 118,  86,  52,  73, 118, 118,  84,
         73,  73,  16,  82,  99,  11, 118,  73,  73,  73, 118,  25,  97,   5,
         11, 118, 118,  19,  87,  31,  25,  91, 119,   8,  59,  84, 112,  73,
         41,  11,  73,  73,  44,  59,  81,  41])
tensor([115,  57,  73,  12,  96,  73,  41,  90, 118,  11, 118, 118, 118,  52,
         61,  13,   4,  30,  94, 118,  53, 115,  31,  72,   5, 107,   9,  86,
        118,   4,  63,  41,  91,  63,  73,  41,  73, 118, 120,  54, 118,  52,
          8, 118,  73,  41,  37,  44,  44, 1

  0%|          | 0/54 [00:00<?, ?it/s]

Epoch [1], Train Loss : [2.59862] Val Loss : [1.84421] Val Score : [0.49671]


  0%|          | 0/213 [00:00<?, ?it/s]

tensor([ 97, 118, 118,  96,  31,  90,  86,  57,  52,  52, 127, 118, 118, 121,
         11,  73,  86,   5,  20,  82,  37,  41,  32, 118,  23, 118,  73, 118,
         73,  90, 118,  44, 118, 118, 101, 118,  86, 118, 118,  20,  41,  15,
        118,  73,  26,  41,  73, 118,  73,  49,   0,   4,  57,  90,  41,  44,
         86,  54, 112,  31,  93,   3,  36,  93])
tensor([100,  93,  41, 118, 118, 118,  53, 118,  73, 118, 115,  85, 118, 118,
          5, 118,  41,  97,  31,  86,  90,  90, 119, 118,  93,  85,  90,  12,
         85,  52,  84,  52,  44,  86, 118, 112,  37,  41,  73, 118,   9,  31,
         31,  85,  31, 118,  61, 118, 120,  32, 118,  54,  86,  58,  35, 112,
        118, 125,  17,  86,  86,  73,  34,  44])
tensor([111,  67,  16,  96, 118,  96,  73,  73,  73, 120,  34,  85, 118, 118,
        127, 115,  73, 118,  96,  90,   8,  61,  53,  73,  58,  82,  28,  73,
         90, 118, 118,  44,  31, 118, 118,   5, 115, 118,  44, 118,  20,  60,
        119, 118, 118,   5,  52,  11,  41, 1

KeyboardInterrupt: 