In [41]:
import torch
import numpy as np
import torch.nn as nn
from torch.nn.utils.rnn import pad_sequence, pack_sequence, pack_padded_sequence, pad_packed_sequence

# 참조
# https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&color_mode=auto&commit=a0e1e9290f0347c0c4be3bc940c7a9e86b3b69d9&device=unknown&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73746174732d6465762f435541495f5079546f7263682f613065316539323930663033343763306334626533626339343063376139653836623362363964392f6c61622d31315f375f5061636b656453657175656e63652e6970796e62&logged_in=false&nwo=stats-dev%2FCUAI_PyTorch&path=lab-11_7_PackedSequence.ipynb&platform=android&repository_id=183885275&repository_type=Repository&version=98


# Random word from random word generator
data = ['hello world',
        'midnight',
        'calculation',
        'path',
        'short circuit']

# Make dictionary
char_set = ['<pad>'] + list(set(char for seq in data for char in seq)) # Get all characters and include pad token
char2idx = {char: idx for idx, char in enumerate(char_set)} # Constuct character to index dictionary
print('char_set:', char_set)
print('char_set length:', len(char_set))















char_set: ['<pad>', ' ', 'l', 'e', 'g', 'o', 'w', 'u', 'p', 'm', 'c', 'r', 'i', 'h', 't', 'd', 's', 'n', 'a']
char_set length: 19


In [42]:
# Convert character to index and make list of tensors
X = [torch.LongTensor([char2idx[char] for char in seq]) for seq in data]

# Check converted result
for sequence in X:
    print(sequence)

tensor([13,  3,  2,  2,  5,  1,  6,  5, 11,  2, 15])
tensor([ 9, 12, 15, 17, 12,  4, 13, 14])
tensor([10, 18,  2, 10,  7,  2, 18, 14, 12,  5, 17])
tensor([ 8, 18, 14, 13])
tensor([16, 13,  5, 11, 14,  1, 10, 12, 11, 10,  7, 12, 14])


In [43]:
# Make length tensor (will be used later in 'pack_padded_sequence' function)
lengths = [len(seq) for seq in X]
print('lengths:', lengths)

lengths: [11, 8, 11, 4, 13]


In [44]:
# Make a Tensor of shape (Batch x Maximum_Sequence_Length)
padded_sequence = pad_sequence(X, batch_first=True) # X is now padded sequence
print(padded_sequence)
print(padded_sequence.shape)

tensor([[13,  3,  2,  2,  5,  1,  6,  5, 11,  2, 15,  0,  0],
        [ 9, 12, 15, 17, 12,  4, 13, 14,  0,  0,  0,  0,  0],
        [10, 18,  2, 10,  7,  2, 18, 14, 12,  5, 17,  0,  0],
        [ 8, 18, 14, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [16, 13,  5, 11, 14,  1, 10, 12, 11, 10,  7, 12, 14]])
torch.Size([5, 13])


In [49]:

embeds = nn.Embedding(10,5)
print(embeds.weight.shape,"\n",embeds.weight)
word = {'hell':0,'world':1}

ten = torch.tensor([0,0,0,9],dtype=torch.long)
print(ten,"\n\n\n","얏호")

emd = embeds(ten)
print(emd.shape,"\n",emd)

torch.Size([10, 5]) 
 Parameter containing:
tensor([[ 0.7059, -1.9180,  0.5313,  0.5144, -0.3707],
        [ 0.9646,  1.0572, -2.0950, -0.0962, -1.6667],
        [-0.8397,  0.0888, -0.1117, -2.0625,  1.2218],
        [ 1.2746, -1.5517, -0.3631, -2.1539, -0.2085],
        [-2.0621, -0.1531,  1.1644,  0.5369, -0.6588],
        [ 0.8500, -1.1765, -1.4831, -0.5402, -0.9016],
        [ 1.4291,  0.1506,  0.3183,  0.3158,  1.2158],
        [-2.1821,  0.3487,  0.4725, -1.8929,  2.4428],
        [ 1.5025, -0.2328,  0.0703, -1.6530, -1.5387],
        [ 0.2614, -0.4773, -0.5584, -1.3951,  0.2097]], requires_grad=True)
tensor([0, 0, 0, 9]) 


 얏호
torch.Size([4, 5]) 
 tensor([[ 0.7059, -1.9180,  0.5313,  0.5144, -0.3707],
        [ 0.7059, -1.9180,  0.5313,  0.5144, -0.3707],
        [ 0.7059, -1.9180,  0.5313,  0.5144, -0.3707],
        [ 0.2614, -0.4773, -0.5584, -1.3951,  0.2097]],
       grad_fn=<EmbeddingBackward>)
