In [2]:
import pandas as pd 


df = pd.read_csv('./train.csv')


In [3]:
cols = ["cat1","cat2","cat3"]
cat_list_data = df[cols].values.tolist()

cat1_list = []
cat2_list = []
cat3_list = []

for x in cat_list_data:
    cat1_list.append(x[0])
    cat2_list.append(x[1])
    cat3_list.append(x[2])

cat1_list = list(set(cat1_list))
cat2_list = list(set(cat2_list))
cat3_list = list(set(cat3_list))

print(cat1_list,"\n",cat2_list,"\n",cat3_list)
print(len(cat1_list),len(cat2_list),len(cat3_list) )

['숙박', '음식', '인문(문화/예술/역사)', '쇼핑', '자연', '레포츠'] 
 ['축제', '문화시설', '건축/조형물', '휴양관광지', '자연관광지', '관광자원', '공연/행사', '쇼핑', '복합 레포츠', '육상 레포츠', '수상 레포츠', '산업관광지', '항공 레포츠', '숙박시설', '레포츠소개', '역사관광지', '체험관광지', '음식점'] 
 ['5일장', '미술관/화랑', '카트', '문화전수시설', '요트', '해안절경', '서양식', '컨벤션', '카지노', '한식', '대형서점', '분수', '바다낚시', '식음료', '스케이트', '성', '헹글라이딩/패러글라이딩', '유원지', '국립공원', '전문상가', '채식전문점', '도립공원', '약수터', '일식', '복합 레포츠', '골프', '계곡', '자연생태관광지', '민물낚시', '빙벽등반', '한옥스테이', '자연휴양림', '도서관', '테마공원', 'ATV', '유적지/사적지', '수목원', '민박', '전시관', '뮤지컬', '이색체험', '중식', '유명건물', '펜션', '섬', '다리/대교', '박물관', '유스호스텔', '유람선/잠수함관광', '민속마을', '영화관', '헬스투어', '번지점프', '학교', '콘도미니엄', '홈스테이', '이색찜질방', 'MTB', '수련시설', '고택', '공예,공방', '이색거리', '산', '농.산.어촌 체험', '생가', '트래킹', '문', '스키(보드) 렌탈샵', '자전거하이킹', '승마', '특산물판매점', '온천/욕장/스파', '등대', '기암괴석', '공원', '동굴', '대중콘서트', '패밀리레스토랑', '호수', '외국문화원', '공연장', '스카이다이빙', '고궁', '연극', '카약/카누', '해수욕장', '박람회', '야영장,오토캠핑장', '수영', '기타', '강', '면세점', '터널', '수상레포츠', '스노쿨링/스킨스쿠버다이빙', '일반축제', '동상', '사격장', '게스트하우스', '컨벤션

In [4]:
list(df['cat1'].value_counts())

[5614, 4912, 2611, 1719, 1434, 696]

In [5]:
list(df['cat2'].value_counts())

[4912,
 2288,
 1578,
 1571,
 1434,
 1220,
 889,
 805,
 696,
 569,
 328,
 277,
 141,
 139,
 93,
 24,
 11,
 11]

In [6]:
print(len(dict(df['cat3'].value_counts())))
print(dict(df['cat3'].value_counts()))


128
{'한식': 3438, '야영장,오토캠핑장': 1558, '바/까페': 785, '유적지/사적지': 622, '일반축제': 549, '사찰': 495, '이색거리': 467, '펜션': 445, '한옥스테이': 404, '모텔': 340, '농.산.어촌 체험': 332, '박물관': 310, '공원': 271, '상설시장': 270, '트래킹': 246, '전시관': 243, '산': 239, '서양식': 226, '유원지': 211, '중식': 209, '자연생태관광지': 207, '해수욕장': 207, '미술관/화랑': 204, '골프': 179, '전문상가': 173, '테마공원': 172, '5일장': 165, '계곡': 160, '일식': 151, '기념탑/기념비/전망대': 148, '항구/포구': 134, '관광단지': 126, '공연장': 120, '민물낚시': 119, '자연휴양림': 118, '문화원': 113, '섬': 111, '유명건물': 105, '강': 104, '수목원': 95, '수련시설': 95, '도서관': 92, '고택': 92, '희귀동.식물': 88, '성': 85, '게스트하우스': 83, '기타': 79, '민속마을': 76, '기타행사': 71, '종교성지': 65, '기념관': 64, '패밀리레스토랑': 61, '스키(보드) 렌탈샵': 60, '홈스테이': 57, '바다낚시': 57, '기암괴석': 53, '온천/욕장/스파': 53, '생가': 43, '다리/대교': 41, '공예,공방': 41, '폭포': 40, '민박': 39, '특산물판매점': 37, '채식전문점': 36, '고궁': 36, '자동차경주': 35, '콘도미니엄': 34, '안보관광': 34, '호수': 30, '유람선/잠수함관광': 30, '박람회': 29, '썰매장': 27, '윈드서핑/제트스키': 27, '수영': 27, '문화전수시설': 26, '해안절경': 25, '등대': 24, '복합 레포츠': 24, '문': 23, '컨벤션

In [63]:
target_str = "동상"

print(df[df['cat3']==target_str]['overview'])
print(list(df[df['cat3']==target_str]['overview']))

153      독립운동가로 우리 민족의 자주독립과 민주주의 발전을 위해 헌신한 해공 신익희 선생의...
429      6.25전쟁에서 위기일발의 포항전투에서 미 제8군 부사령관으로 북한의 침입을 막아내...
1687     조국을 위해 기꺼이 목숨을 바쳤던 나석주 의사의 숭고한 희생정신을 추모하기 위해 현...
1805     헤이그 밀사로 특파되어 일제 침략의 부당함을 알린 이준 열사를 기리기 위하여 장충단...
2987     성재 이시영 선생은 일제에 국권을 빼앗긴 당시, 형 건영ㆍ석영ㆍ 철영ㆍ 회영, 동생...
3699     춘천시립도서관 뒷 정원 왼쪽에는 일제강점기에 여성 독립운동가로 활동한 윤희순 여사의...
4279     천안 아우내 장터에서 독립만세운동을 주동하다 체포되어 옥중에서 순국한 유관순 열사를...
4704     대한제국 말기 및 일제 강점기 시절 교육자이자 애국계몽가인 남강 이승훈 선생의 공적...
6310     * 광개토태왕비<br /><br />국강상광개토경평안호태왕비(國岡上廣開土境平安好太王...
6688     이원등 상사는 1966년 2월 4일 공수특전단 고공침투 낙하조장으로 고공강하 훈련 ...
8110     * 백제 여인의 망부상을 정읍사의 상징물로 *<br /><br />정읍에 정읍사공원...
10248    이회영은 이조판서 이유승의 4남으로 태어나 성장했다. 1905년에 을사늑약 체결의 ...
11323    천안 아우내 장터에서 독립만세운동을 주동하다 체포되어 옥중에서 순국한 유관순 열사의...
12629    설악해맞이공원 뒤편 바닷가에 세워진 조각상이다. 갯바위 위에 연인처럼 보이는 한 쌍...
13830    광화문의 충무공 이순신 장군 동상은 정부의 산하 단체였던 애국선열 조상건립위원회와 ...
16219    6.25전쟁 당시 가장 치열했던 백마고지 전투에서 육탄으로 적의 진지를 공격해 승리...
16293    독립운동가, 교육자, 정치가이자 민족지도자로 활동한 고하 송진우 선생을 추모하기 위.

In [8]:

# ATV
# 4958

# 빙벽등반
# 5113,6992(캠핑장)

# 클럽 (양조장,막걸리 술집)
# 15876,7780

# 터널
# 1210(장미터널 ㅋㅋ)

# 학교
# 10715 - 홀로세 생태보존연구소 - 애매함

# 식음료
# 1131(이것도 터널이겟네?)


# 서비스드레지던스 -> 호텔 + 다양한거

# 요트
# 1031(수상레포츠랑 겹침),16684(테마공원)

# 자전거
# 12282 (MTB랑 겹침)


import numpy as np
# print(np.mean(list(df['cat3'].value_counts())))
# print(np.median(list(df['cat3'].value_counts())))

temp = list(df['cat3'].value_counts())
print(temp)
# print(temp[2:-13])
# print(np.median(temp[2:-13]))

# print(len(temp),len(temp)*0.9)
# print(int((len(temp)-(len(temp)*0.9))/2),)
rate = int((len(temp)-(len(temp)*0.90))/2)
print(temp[rate:-rate])
print(np.median(temp[rate:-rate]))

[3438, 1558, 785, 622, 549, 495, 467, 445, 404, 340, 332, 310, 271, 270, 246, 243, 239, 226, 211, 209, 207, 207, 204, 179, 173, 172, 165, 160, 151, 148, 134, 126, 120, 119, 118, 113, 111, 105, 104, 95, 95, 92, 92, 88, 85, 83, 79, 76, 71, 65, 64, 61, 60, 57, 57, 53, 53, 43, 41, 41, 40, 39, 37, 36, 36, 35, 34, 34, 30, 30, 29, 27, 27, 27, 26, 25, 24, 24, 23, 22, 21, 21, 20, 20, 20, 18, 18, 17, 17, 15, 15, 13, 12, 12, 12, 11, 11, 11, 11, 10, 10, 9, 9, 9, 8, 8, 7, 7, 7, 6, 6, 6, 6, 6, 5, 4, 4, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2]
[467, 445, 404, 340, 332, 310, 271, 270, 246, 243, 239, 226, 211, 209, 207, 207, 204, 179, 173, 172, 165, 160, 151, 148, 134, 126, 120, 119, 118, 113, 111, 105, 104, 95, 95, 92, 92, 88, 85, 83, 79, 76, 71, 65, 64, 61, 60, 57, 57, 53, 53, 43, 41, 41, 40, 39, 37, 36, 36, 35, 34, 34, 30, 30, 29, 27, 27, 27, 26, 25, 24, 24, 23, 22, 21, 21, 20, 20, 20, 18, 18, 17, 17, 15, 15, 13, 12, 12, 12, 11, 11, 11, 11, 10, 10, 9, 9, 9, 8, 8, 7, 7, 7, 6, 6, 6, 6, 6, 5, 4, 4, 4, 4, 4, 4,

In [9]:
df 

id                       img_path  \
0      TRAIN_00000  ./image/train/TRAIN_00000.jpg   
1      TRAIN_00001  ./image/train/TRAIN_00001.jpg   
2      TRAIN_00002  ./image/train/TRAIN_00002.jpg   
3      TRAIN_00003  ./image/train/TRAIN_00003.jpg   
4      TRAIN_00004  ./image/train/TRAIN_00004.jpg   
...            ...                            ...   
16981  TRAIN_16981  ./image/train/TRAIN_16981.jpg   
16982  TRAIN_16982  ./image/train/TRAIN_16982.jpg   
16983  TRAIN_16983  ./image/train/TRAIN_16983.jpg   
16984  TRAIN_16984  ./image/train/TRAIN_16984.jpg   
16985  TRAIN_16985  ./image/train/TRAIN_16985.jpg   

                                                overview          cat1  \
0      소안항은 조용한 섬으로 인근해안이 청정해역으로 일찍이 김 양식을 해서 높은 소득을 ...            자연   
1      경기도 이천시 모가면에 있는 골프장으로 대중제 18홀이다. 회원제로 개장을 했다가 ...           레포츠   
2      금오산성숯불갈비는 한우고기만을 전문적으로 취급하고 사용하는 부식 자재 또한 유기농법...            음식   
3      철판 위에서 요리하는 안동찜닭을 맛볼 수 있는 곳이다. 경상북도 안동시에 있는 한식...            음식   
4      ※ 영업시간 10:30 ~ 20:30\n\n3대에 걸쳐 아귀만을 전문으로 취급하는 ...            음식   
...                                                  ...           ...   
16981  해발 12000m에 자리한 식담겸 카페점문점이다.<br>곤드레밥과 감자전을 판매하고...            음식   
16982  설악힐호텔은 동해고속도로 속초톨게이트에서 멀지 않은 관광로 변에 있다. 속초의 대표...            숙박   
16983  충남 서산시 중심가에 위치한 줌모텔은 프라이버스가 보장되는 조용한 공간으로 가치가 ...            숙박   
16984  토토큰바위캠핑장은 경기도 가평지역 내에서도 청정지역으로 손꼽히는 지역으로 주변에 화...           레포츠   
16985  포천의 진산으로 불리우는 왕방산(王訪山)에는 천년의 역사를 간직하고 있는 왕산사(王...  인문(문화/예술/역사)   

         cat2       cat3  
0       자연관광지      항구/포구  
1      육상 레포츠         골프  
2         음식점         한식  
3         음식점         한식  
4         음식점         한식  
...       ...        ...  
16981     음식점         한식  
16982    숙박시설         모텔  
16983    숙박시설         모텔  
16984  육상 레포츠  야영장,오토캠핑장  
16985   역사관광지         사찰  

[16986 rows x 6 columns]

In [10]:
from torch.utils.data import random_split, DataLoader,Dataset
from sklearn.model_selection import train_test_split
import torch
import numpy as np
import collections

class CustomDataset(Dataset):
    def __init__(self, x_tensor, y_tensor):
        self.x = x_tensor
        self.y = y_tensor

    def __getitem__(self, index):
        return (self.x[index], self.y[index])

    def __len__(self):
        return len(self.x)
    
    


X = np.random.randn(100, 2)
y = np.array([0]*10+[1]*10 +[2]*80)
# print(y)
c = collections.Counter(y)
print(dict(c))





X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1,stratify=y)

print(y_train)
print(y_test)
# for item in val:
#     label.append(item[1])
    
# print(label)


# train_dataset = Dataset(X_train, y_train, ...)
# train_loader = DataLoader(train_dataset, ...)

{0: 10, 1: 10, 2: 80}
[2 2 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 1 2 2 2 2 1 2 2 1 2 0
 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 0 2 0 0 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 1 2 1 2 2 2 0 2 1 2]
[2 2 2 2 2 2 2 2 0 1]


In [11]:
import torch.nn.functional as F

z = torch.FloatTensor([1, 0, 0,0,0])
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.4046, 0.1488, 0.1488, 0.1488, 0.1488])


In [12]:
import numpy as np
import torch
import torch.nn.functional as F
vars = torch.Tensor([[ 4.3119e-01, -8.0810e-01, -4.2794e-01, -5.8002e-01, -1.3576e+00,
         -2.6954e-01, -1.0584e+00,  7.8035e-01,  7.9913e-01, -1.0199e+00,
         -5.1140e-01, -3.5833e-01,  2.0144e-01, -2.7200e-01,  3.6030e-01,
         -2.1461e+00, -1.3983e+00, -5.3143e-01,  2.0246e-01, -1.1527e+00,
          1.0328e+00, -1.6050e+00, -7.8554e-01, -4.2815e-01, -3.3489e-01,
         -5.9107e-02, -1.1913e+00, -1.6181e+00, -1.9258e+00, -1.0162e+00,
         -7.5647e-01,  3.3376e-01, -2.0889e+00, -3.9115e-01, -7.9394e-01,
         -2.6711e+00, -1.4482e+00, -3.4761e-01,  3.0881e-01,  2.7093e-01,
         -1.4065e+00,  1.8367e+00, -1.5872e+00, -1.4431e+00,  3.9869e-01,
         -8.9559e-01, -5.8691e-01, -1.1147e+00, -1.7973e+00, -1.2712e+00,
         -1.0664e+00, -7.4211e-01,  1.3909e-01,  6.6510e-01,  1.1486e+00,
          4.3795e-01, -6.4472e-01,  2.3074e+00, -2.3743e-01, -9.8901e-01,
         -6.3997e-01,  1.1844e-01, -1.1788e+00, -7.3022e-01, -1.4279e+00,
         -1.2802e+00, -1.9684e+00,  6.5703e-01, -5.9888e-01, -1.4800e+00,
         -9.4194e-01, -1.1184e-01, -2.5883e+00,  1.9547e-01, -1.3004e+00,
         -9.8085e-01, -8.1600e-01, -3.8695e-01, -1.3499e+00, -1.3389e+00,
         -9.2043e-01, -1.1603e+00, -6.1745e-01, -2.2980e-01,  1.9571e-01,
         -4.3199e-01,  1.1849e+00, -6.1313e-01, -4.3662e-01, -6.6083e-01,
          5.2700e-01,  3.3832e+00, -8.0868e-01, -1.0946e+00, -8.9969e-02,
         -2.0865e+00, -1.7556e-02, -4.5731e-01, -1.3446e+00, -1.1352e+00,
          2.6128e+00,  2.2862e+00, -1.4443e+00, -9.4407e-01, -1.6078e+00,
         -1.2790e+00, -1.2825e+00, -1.0048e+00, -3.4254e-01,  4.9879e-01,
         -1.2299e+00, -7.5469e-02, -7.1173e-01,  1.7847e-03,  1.6790e+00,
          9.4315e-01, -6.8021e-01, -6.5329e-01,  1.0550e+01, -2.3137e-01,
         -3.4474e-01,  2.6978e-01, -1.0360e+00, -7.4086e-01, -1.1071e+00,
         -6.3777e-01,  8.0218e-02, -7.2704e-01],
        [ 1.6918e-01, -1.0398e+00, -8.0937e-01, -3.3400e-01, -1.4361e+00,
         -4.4789e-02, -1.2948e+00,  5.6749e-01,  3.4227e-01, -1.1575e+00,
         -6.9062e-01, -4.7267e-01,  3.8973e-01, -4.7515e-01,  2.5680e-01,
         -1.9973e+00, -1.4357e+00, -6.4647e-01,  5.9736e-01, -1.0825e+00,
          1.5268e+00, -1.6725e+00, -1.1825e+00, -6.9106e-01, -7.1303e-01,
         -3.0863e-01, -1.1173e+00, -1.9512e+00, -2.1046e+00, -9.4439e-01,
         -1.2131e+00,  8.7916e-01, -2.3578e+00, -3.0706e-01, -7.3275e-01,
         -2.9211e+00, -1.8805e+00, -4.8357e-01,  3.5123e-01,  1.1021e+00,
         -1.0777e+00,  9.4486e-01, -1.4610e+00, -1.6242e+00,  2.9227e-01,
         -1.1038e+00, -1.1078e+00, -1.4886e+00, -1.7745e+00, -1.5288e+00,
         -1.3315e+00, -1.1942e+00,  4.1082e-01,  5.4587e-01,  1.1288e+00,
          4.3615e-01, -7.9792e-01,  1.1142e+00, -1.0968e-02, -1.0724e+00,
         -6.2179e-01,  2.7034e-01, -1.3988e+00, -7.5446e-01, -1.6463e+00,
         -1.4164e+00, -2.1094e+00,  5.8585e-01, -1.0756e+00, -1.6979e+00,
         -1.2927e+00, -3.5958e-01, -2.5031e+00,  1.2115e+00, -1.5252e+00,
         -1.4282e+00, -1.0157e+00, -1.4629e-01, -1.6904e+00, -1.7928e+00,
         -1.1022e+00, -1.4128e+00, -8.4650e-01, -1.5778e-01,  1.2963e-01,
         -2.0977e-01,  2.1659e+00, -8.5130e-01, -6.6651e-01, -9.4773e-01,
          9.9271e-01,  3.0265e+00, -1.3765e+00, -6.5973e-01,  3.2197e-01,
         -1.9845e+00, -1.7986e-01, -2.3167e-01, -1.8213e+00, -1.5664e+00,
          1.5847e+00,  1.8467e+00, -1.5673e+00, -1.3361e+00, -1.9196e+00,
         -1.3879e+00, -1.4812e+00, -1.1439e+00, -4.9938e-01, -2.0645e-01,
         -1.5128e+00,  1.7496e-01, -3.8723e-01, -4.3844e-01,  1.2111e+00,
          1.5425e+00, -6.2206e-01, -9.8054e-01,  1.0268e+01,  9.3964e-02,
         -3.8448e-01,  6.3645e-01, -1.1029e+00, -9.9204e-01, -1.3381e+00,
         -8.2582e-01,  1.6175e-01, -8.8550e-01]])

In [13]:
hypothesis = F.softmax(vars, dim=1)
print(hypothesis)
print(torch.sum(hypothesis[0]))

tensor([[4.0145e-05, 1.1626e-05, 1.7003e-05, 1.4604e-05, 6.7107e-06, 1.9921e-05,
         9.0513e-06, 5.6921e-05, 5.8000e-05, 9.4066e-06, 1.5641e-05, 1.8228e-05,
         3.1905e-05, 1.9872e-05, 3.7398e-05, 3.0502e-06, 6.4431e-06, 1.5331e-05,
         3.1937e-05, 8.2368e-06, 7.3267e-05, 5.2399e-06, 1.1891e-05, 1.6999e-05,
         1.8661e-05, 2.4587e-05, 7.9249e-06, 5.1717e-06, 3.8019e-06, 9.4414e-06,
         1.2242e-05, 3.6418e-05, 3.2298e-06, 1.7640e-05, 1.1791e-05, 1.8044e-06,
         6.1295e-06, 1.8425e-05, 3.5521e-05, 3.4200e-05, 6.3905e-06, 1.6370e-04,
         5.3340e-06, 6.1608e-06, 3.8861e-05, 1.0652e-05, 1.4504e-05, 8.5558e-06,
         4.3233e-06, 7.3163e-06, 8.9792e-06, 1.2419e-05, 2.9976e-05, 5.0725e-05,
         8.2262e-05, 4.0417e-05, 1.3689e-05, 2.6210e-04, 2.0571e-05, 9.7017e-06,
         1.3754e-05, 2.9363e-05, 8.0246e-06, 1.2567e-05, 6.2552e-06, 7.2508e-06,
         3.6434e-06, 5.0317e-05, 1.4331e-05, 5.9376e-06, 1.0169e-05, 2.3324e-05,
         1.9601e-06, 3.1715e